env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - EMU_FLAVOR=default
  - ANDROID_HOME=/usr/local/android-sdk
  - TOOLS=${ANDROID_HOME}/tools
  - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  - API=28
  - ABI=x86
  - AUDIO=-no-audio
language: android
dist: trusty
android:
  components:
  - tools
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
- chmod +x gradlew
- gem update --system
- gem install bundler
- bundle install
- echo 'count=0' > /home/travis/.android/repositories.cfg
- echo y | sdkmanager "platform-tools" >/dev/null
- echo y | sdkmanager "tools" >/dev/null
- echo y | sdkmanager "build-tools;28.0.3" >/dev/null
- echo y | sdkmanager "platforms;android-$API" >/dev/null
- echo y | sdkmanager --channel=4 "emulator"
- echo y | sdkmanager "extras;android;m2repository" >/dev/null
script:
- "./gradlew clean assembleDebug"
before_deploy:
- openssl aes-256-cbc -K $encrypted_41783dd8bae9_key -iv $encrypted_41783dd8bae9_iv
  -in signing.tar.enc -out signing.tar -d
- tar xvf signing.tar
- fastlane alpha
deploy:
  provider: releases
  api_key:
    secure: U21XKaO+J4JoPiOgdNLyxTFCnM635lMO4rRlt3rPT/AJ5AA8Uev+g2mu3nyXhl3AEOe8KkJrdAFCgJG66cV0UT+fyNkhm/K/ABpeMcV0ZBPBh/L/liM2Icky/cCbYsrll444CBZBEe4dr0qXP/MYpB3NduaXn8x3pgqg2WP6EimO/ei/nzwBU9vaIjJOdk5vmCwKF5duNVtDrG5P1DqF2ic/rT5NCK15LjnSW2kGNynK1DuS1lWK6IsuPtUbtUPVBbgPmclU9C48SjTp1pDyNSWkONxT/SOmwHgiSzfWfaWUAvQEDLyhzQAVRXb/Y65dJCeXjMwYJeoTgF+r9ptqXR+a9BxEhAcXloKtfNyxOFFtqII0VaJWrfqdYGu8XJxjsxOvvnIBppzm556A42TEeWaXVJAidCPm7BAk+zjEh+9LhTv9pgzmpYde7cH8JKiTOzNksZ1YJhZFQe68KNh8rVcPYjn7LGtNHtQMMhZG+oxXpUWQRUr/pg4UHHH50clWzYeR7Oe5XYlyl0TFuaz9h8m5GJgrlLdSw8hKRK6Kx13Vq7U0pUMc+Q4EXVGxv7gkezm/dDxXWe9fAn4KcOTxP8verT9dXHdPOZgKsyGBYNThpawjV/tWQ53Zvepzq2IgA70mN672MKhfrmAocwK1uMXCfWC9+GIDOEMJVZbI8Gw=
  file_glob: true
  file: "app/build/outputs/bundle/release/*.aab"
  skip_cleanup: true
  on:
    repo: TheCacophonyProject/sidekick
    tags: true
