require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.1'
use_frameworks!
# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.5.0_@capacitor+core@4.5.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.5.0_@capacitor+core@4.5.0/node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
