-keep,includedescriptorclasses class net.sqlcipher.** { *; }
-keep,includedescriptorclasses interface net.sqlcipher.** { *; }
-dontwarn okhttp3.**
-keep class okhttp3.* { }
-dontwarn okio.**
-dontwarn org.slf4j.**